<?php

/**
 * @file
 * Reworked standard login form to ajax.
 */

require_once('includes/ajax_login.callback.inc');
/**
 * Implements hook_form_alter().
 */
function ajax_login_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_block':
      /*$form['files'] = '/includes/ajax_login.callback.inc';*/
      $registration_allowed = variable_get('user_register');
      if ($registration_allowed) {
        $user_register_link = array(
          '#type' => 'link',
          '#title' => t('Create new account'),
          '#href' => 'user/register/',
        );
      }
      $user_password_link = array(
        '#type' => 'link',
        '#title' => t('Request new password'),
        '#href' => 'user/password/',
      );
      $items[] = render($user_register_link);
      $items[] = render($user_password_link);
      $form['links'] = array(
        '#theme' => 'item_list',
        '#items' => $items,
      );
    case 'user_login':
      $form['actions']['submit']['#ajax'] = array(
        'callback' => 'ajax_login_ajax_callback',
      );
      break;
  }
}
