<?php

/**
 * Implements hook_form_alter().
 */
function ajax_login_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'user_login_block':
      $registration_allowed = variable_get('user_register');
      if ($registration_allowed) {
        $user_register_link = array(
          '#type' => 'link',
          '#title' => t('Create new account'),
          '#href' => 'user/register/',
        );
      }
      $user_password_link = array(
        '#type' => 'link',
        '#title' => t('Request new password'),
        '#href' => 'user/password/',
      );
      $items[] = render($user_register_link);
      $items[] = render($user_password_link);
      $form['links'] = array(
        '#theme' => 'item_list',
        '#items' => $items,
      );
    case 'user_login':
      $form['messages'] = array(
        '#markup' => '<div id="ajax-login-messages"></div>',
      );
      $form['actions']['submit']['#ajax'] = array(
        'callback' => 'ajax_login_ajax_callback',
      );
      break;
  }
}

/**
 * Add user.pages.inc for enabling user_pass_validate() and user_pass_submit().
 */
function ajax_login_user_pass_after_build($form, &$form_state) {
  module_load_include('pages.inc', 'user');
  return $form;
}

/**
 * Ajax callback for user login form.
 */
function ajax_login_ajax_callback($form, &$form_state) {
  $commands = array();
  if (!form_get_error()) {
    drupal_set_message(t('Hello! To see the site as a registered user, click on <a href="/">link</a>.'));
    hide($form);
  }
  /* do something */
  $commands[] = ajax_command_html('#ajax-login-messages', theme('status_messages'));
  return array('#type' => 'ajax', '#commands' => $commands);
}
