<?php

/**
 * @file
 * Validate fields an forms.
 */

/**
 * Validate function for internet_reception_page_form.
 * @param array $form
 *    Form elements.
 * @param array $form_state
 *    An array which stores information about the form.
 */
function internet_reception_form_validate($form, $form_state) {
/*  if ($form_state['values']['age'] <= -1) {
    form_set_error('age', t('Age can not be negative'));
  }
  if ($form_state['values']['age'] == 0) {
    form_set_error('age', t('Age is not equal to 0'));
  }
  if (ctype_alnum($form_state['values']['age'] == 0)) {
    form_set_error('age', t('Only numbers!'));
  }
  if (is_float($form_state['values']['age']) == TRUE) {
    form_set_error('age', t('Is not an integer'));
  }
  if (ctype_digit($form_state['values']['full_name'])) {
    form_set_error('full_name', t('Only text!'));
  }*/
}
